<?php

return [
    'oracle' => [
        'driver'         => 'oracle',
        'host'           => '203.153.96.250',
        'port'           => '1521',
        'database'       => 'ORION',
        'username'       => 'ENDUSER',
        'password'       => 'Nu5er123',
        'service_name' => 'ORION',
    ],
    'PTSMCB' => [
        'driver'         => 'oracle',
        'host'           => '203.153.96.250',
        'port'           => '1521',
        'database'       => 'ORION',
        'username'       => 'PTSMCB',
        'password'       => 'ERP0231204697B1916LJ',
        'service_name' => 'ORION',
    ],
    'PTSEIT' => [
        'driver'         => 'oracle',
        'host'           => '203.153.96.250',
        'port'           => '1521',
        'database'       => 'ORION',
        'username'       => 'PTSEIT',
        'password'       => 'ERP0231204697B1916LJ',
        'service_name' => 'ORION',
    ],
    'PTSEIB' => [
        'driver'         => 'oracle',
        'host'           => '203.153.96.250',
        'port'           => '1521',
        'database'       => 'ORION',
        'username'       => 'PTSEIB',
        'password'       => 'ERP0231204697B1916LJ',
        'service_name' => 'ORION',
    ],
    'PTRJB' => [
        'driver'         => 'oracle',
        'host'           => '203.153.96.251',
        'port'           => '1521',
        'database'       => 'ORION',
        'username'       => 'PTRJB',
        'password'       => 'ERP0231204697B1916LJ',
        'service_name' => 'ORION',
    ],
    'PTRPM' => [
        'driver'         => 'oracle',
        'host'           => '203.153.96.251',
        'port'           => '1521',
        'database'       => 'ORION',
        'username'       => 'PTRPM',
        'password'       => 'ERP0231204697B1916LJ',
        'service_name' => 'ORION',
    ],
    'SMEC' => [
        'driver'         => 'oracle',
        'host'           => '203.153.96.253',
        'port'           => '1521',
        'database'       => 'ORION',
        'username'       => 'SMEC',
        'password'       => 'ERP0231204697B1916LJ',
        'service_name' => 'ORION',
    ],
];
