<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\DB;

class MailController extends Controller
{
        public function basic_email()
        {
                // $data = array('name' => "IT");

                // Mail::send(['text' => 'mail'], $data, function ($message) {
                //     $message->to('opayabumanyu@gmail.com', 'DATA')->subject('REPORT');
                //     $message->from('naufal@smcindonesia.com', 'IT');
                // });
                // echo "Basic Email Sent. Check your inbox.";
                $ptsmcb = DB::connection('PTSMCB')->select("
        SELECT
NVL(A.ERP,B.ERP) AS ERP
, NVL(A.BRAND,B.BRAND) AS BRAND
, NVL(B.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM'), 'YYYYMM')) AS OLD_PERIODE
, 'Rp. ' || TO_CHAR(NVL(B.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS OLD_DATA
, NVL(A.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'),'YYYYMM')) AS NEW_PERIODE
, 'Rp. ' || TO_CHAR(NVL(A.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS NEW_DATA
, 'Rp. ' || TO_CHAR((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)),'999,999,999,999,999') AS SELISIH
, CASE 
	WHEN NVL(B.TOTAL_DSI_DPP_NET,0) != 0 THEN
		TO_CHAR(((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)) / B.TOTAL_DSI_DPP_NET * 100),'999,999,999,999,999') || '%'
	ELSE
		0 || '%'
END AS SELISIH_PERSEN
, NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0) AS ANGKA
FROM 
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
AND DSI_DATE < TRUNC(SYSDATE, 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) A
FULL JOIN
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM')
AND DSI_DATE < TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) B ON A.ERP = B.ERP AND A.BRAND = B.BRAND
        ");

                $ptseit = DB::connection('PTSEIT')->select("
        SELECT
NVL(A.ERP,B.ERP) AS ERP
, NVL(A.BRAND,B.BRAND) AS BRAND
, NVL(B.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM'), 'YYYYMM')) AS OLD_PERIODE
, 'Rp. ' || TO_CHAR(NVL(B.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS OLD_DATA
, NVL(A.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'),'YYYYMM')) AS NEW_PERIODE
, 'Rp. ' || TO_CHAR(NVL(A.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS NEW_DATA
, 'Rp. ' || TO_CHAR((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)),'999,999,999,999,999') AS SELISIH
, CASE 
	WHEN NVL(B.TOTAL_DSI_DPP_NET,0) != 0 THEN
		TO_CHAR(((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)) / B.TOTAL_DSI_DPP_NET * 100),'999,999,999,999,999') || '%'
	ELSE
		0 || '%'
END AS SELISIH_PERSEN
, NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0) AS ANGKA
FROM 
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
AND DSI_DATE < TRUNC(SYSDATE, 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) A
FULL JOIN
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM')
AND DSI_DATE < TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) B ON A.ERP = B.ERP AND A.BRAND = B.BRAND
        ");

                $ptseib = DB::connection('PTSEIB')->select("
        SELECT
NVL(A.ERP,B.ERP) AS ERP
, NVL(A.BRAND,B.BRAND) AS BRAND
, NVL(B.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM'), 'YYYYMM')) AS OLD_PERIODE
, 'Rp. ' || TO_CHAR(NVL(B.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS OLD_DATA
, NVL(A.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'),'YYYYMM')) AS NEW_PERIODE
, 'Rp. ' || TO_CHAR(NVL(A.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS NEW_DATA
, 'Rp. ' || TO_CHAR((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)),'999,999,999,999,999') AS SELISIH
, CASE 
	WHEN NVL(B.TOTAL_DSI_DPP_NET,0) != 0 THEN
		TO_CHAR(((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)) / B.TOTAL_DSI_DPP_NET * 100),'999,999,999,999,999') || '%'
	ELSE
		0 || '%'
END AS SELISIH_PERSEN
, NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0) AS ANGKA
FROM 
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
AND DSI_DATE < TRUNC(SYSDATE, 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) A
FULL JOIN
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM')
AND DSI_DATE < TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) B ON A.ERP = B.ERP AND A.BRAND = B.BRAND
        ");

                $ptrjb = DB::connection('PTRJB')->select("
        SELECT
NVL(A.ERP,B.ERP) AS ERP
, NVL(A.BRAND,B.BRAND) AS BRAND
, NVL(B.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM'), 'YYYYMM')) AS OLD_PERIODE
, 'Rp. ' || TO_CHAR(NVL(B.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS OLD_DATA
, NVL(A.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'),'YYYYMM')) AS NEW_PERIODE
, 'Rp. ' || TO_CHAR(NVL(A.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS NEW_DATA
, 'Rp. ' || TO_CHAR((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)),'999,999,999,999,999') AS SELISIH
, CASE 
	WHEN NVL(B.TOTAL_DSI_DPP_NET,0) != 0 THEN
		TO_CHAR(((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)) / B.TOTAL_DSI_DPP_NET * 100),'999,999,999,999,999') || '%'
	ELSE
		0 || '%'
END AS SELISIH_PERSEN
, NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0) AS ANGKA
FROM 
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
AND DSI_DATE < TRUNC(SYSDATE, 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) A
FULL JOIN
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM')
AND DSI_DATE < TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) B ON A.ERP = B.ERP AND A.BRAND = B.BRAND
        ");

                $ptrpm = DB::connection('PTRPM')->select("
        SELECT
NVL(A.ERP,B.ERP) AS ERP
, NVL(A.BRAND,B.BRAND) AS BRAND
, NVL(B.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM'), 'YYYYMM')) AS OLD_PERIODE
, 'Rp. ' || TO_CHAR(NVL(B.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS OLD_DATA
, NVL(A.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'),'YYYYMM')) AS NEW_PERIODE
, 'Rp. ' || TO_CHAR(NVL(A.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS NEW_DATA
, 'Rp. ' || TO_CHAR((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)),'999,999,999,999,999') AS SELISIH
, CASE 
	WHEN NVL(B.TOTAL_DSI_DPP_NET,0) != 0 THEN
		TO_CHAR(((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)) / B.TOTAL_DSI_DPP_NET * 100),'999,999,999,999,999') || '%'
	ELSE
		0 || '%'
END AS SELISIH_PERSEN
, NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0) AS ANGKA
FROM 
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
AND DSI_DATE < TRUNC(SYSDATE, 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) A
FULL JOIN
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM')
AND DSI_DATE < TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) B ON A.ERP = B.ERP AND A.BRAND = B.BRAND
        ");

                return view('mail2', compact('ptsmcb', 'ptseib', 'ptseit', 'ptrjb', 'ptrpm'));
        }
        public function html_email()
        {
                // START PENGIRIMAN DATA -1 BULAN
                $ptsmcb = DB::connection('PTSMCB')->select("
        SELECT
NVL(A.ERP,B.ERP) AS ERP
, NVL(A.BRAND,B.BRAND) AS BRAND
, NVL(B.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM'), 'YYYYMM')) AS OLD_PERIODE
, 'Rp. ' || TO_CHAR(NVL(B.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS OLD_DATA
, NVL(A.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'),'YYYYMM')) AS NEW_PERIODE
, 'Rp. ' || TO_CHAR(NVL(A.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS NEW_DATA
, 'Rp. ' || TO_CHAR((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)),'999,999,999,999,999') AS SELISIH
, CASE 
	WHEN NVL(B.TOTAL_DSI_DPP_NET,0) != 0 THEN
		TO_CHAR(((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)) / B.TOTAL_DSI_DPP_NET * 100),'999,999,999,999,999') || '%'
	ELSE
		0 || '%'
END AS SELISIH_PERSEN
, NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0) AS ANGKA
FROM 
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
AND DSI_DATE < TRUNC(SYSDATE, 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) A
FULL JOIN
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM')
AND DSI_DATE < TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) B ON A.ERP = B.ERP AND A.BRAND = B.BRAND
        ");

                $ptseit = DB::connection('PTSEIT')->select("
        SELECT
NVL(A.ERP,B.ERP) AS ERP
, NVL(A.BRAND,B.BRAND) AS BRAND
, NVL(B.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM'), 'YYYYMM')) AS OLD_PERIODE
, 'Rp. ' || TO_CHAR(NVL(B.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS OLD_DATA
, NVL(A.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'),'YYYYMM')) AS NEW_PERIODE
, 'Rp. ' || TO_CHAR(NVL(A.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS NEW_DATA
, 'Rp. ' || TO_CHAR((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)),'999,999,999,999,999') AS SELISIH
, CASE 
	WHEN NVL(B.TOTAL_DSI_DPP_NET,0) != 0 THEN
		TO_CHAR(((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)) / B.TOTAL_DSI_DPP_NET * 100),'999,999,999,999,999') || '%'
	ELSE
		0 || '%'
END AS SELISIH_PERSEN
, NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0) AS ANGKA
FROM 
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
AND DSI_DATE < TRUNC(SYSDATE, 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) A
FULL JOIN
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM')
AND DSI_DATE < TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) B ON A.ERP = B.ERP AND A.BRAND = B.BRAND
        ");

                $ptseib = DB::connection('PTSEIB')->select("
        SELECT
NVL(A.ERP,B.ERP) AS ERP
, NVL(A.BRAND,B.BRAND) AS BRAND
, NVL(B.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM'), 'YYYYMM')) AS OLD_PERIODE
, 'Rp. ' || TO_CHAR(NVL(B.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS OLD_DATA
, NVL(A.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'),'YYYYMM')) AS NEW_PERIODE
, 'Rp. ' || TO_CHAR(NVL(A.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS NEW_DATA
, 'Rp. ' || TO_CHAR((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)),'999,999,999,999,999') AS SELISIH
, CASE 
	WHEN NVL(B.TOTAL_DSI_DPP_NET,0) != 0 THEN
		TO_CHAR(((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)) / B.TOTAL_DSI_DPP_NET * 100),'999,999,999,999,999') || '%'
	ELSE
		0 || '%'
END AS SELISIH_PERSEN
, NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0) AS ANGKA
FROM 
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
AND DSI_DATE < TRUNC(SYSDATE, 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) A
FULL JOIN
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM')
AND DSI_DATE < TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) B ON A.ERP = B.ERP AND A.BRAND = B.BRAND
        ");

                $ptrjb = DB::connection('PTRJB')->select("
        SELECT
NVL(A.ERP,B.ERP) AS ERP
, NVL(A.BRAND,B.BRAND) AS BRAND
, NVL(B.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM'), 'YYYYMM')) AS OLD_PERIODE
, 'Rp. ' || TO_CHAR(NVL(B.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS OLD_DATA
, NVL(A.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'),'YYYYMM')) AS NEW_PERIODE
, 'Rp. ' || TO_CHAR(NVL(A.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS NEW_DATA
, 'Rp. ' || TO_CHAR((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)),'999,999,999,999,999') AS SELISIH
, CASE 
	WHEN NVL(B.TOTAL_DSI_DPP_NET,0) != 0 THEN
		TO_CHAR(((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)) / B.TOTAL_DSI_DPP_NET * 100),'999,999,999,999,999') || '%'
	ELSE
		0 || '%'
END AS SELISIH_PERSEN
, NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0) AS ANGKA
FROM 
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
AND DSI_DATE < TRUNC(SYSDATE, 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) A
FULL JOIN
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM')
AND DSI_DATE < TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) B ON A.ERP = B.ERP AND A.BRAND = B.BRAND
        ");

                $ptrpm = DB::connection('PTRPM')->select("
        SELECT
NVL(A.ERP,B.ERP) AS ERP
, NVL(A.BRAND,B.BRAND) AS BRAND
, NVL(B.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM'), 'YYYYMM')) AS OLD_PERIODE
, 'Rp. ' || TO_CHAR(NVL(B.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS OLD_DATA
, NVL(A.PERIODE,TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'),'YYYYMM')) AS NEW_PERIODE
, 'Rp. ' || TO_CHAR(NVL(A.TOTAL_DSI_DPP_NET,0),'999,999,999,999,999') AS NEW_DATA
, 'Rp. ' || TO_CHAR((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)),'999,999,999,999,999') AS SELISIH
, CASE 
	WHEN NVL(B.TOTAL_DSI_DPP_NET,0) != 0 THEN
		TO_CHAR(((NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0)) / B.TOTAL_DSI_DPP_NET * 100),'999,999,999,999,999') || '%'
	ELSE
		0 || '%'
END AS SELISIH_PERSEN
, NVL(A.TOTAL_DSI_DPP_NET,0) - NVL(B.TOTAL_DSI_DPP_NET,0) AS ANGKA
FROM 
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
AND DSI_DATE < TRUNC(SYSDATE, 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) A
FULL JOIN
(SELECT 
ERP
,TO_CHAR(DSI_DATE, 'YYYYMM') PERIODE
,BRAND
,NVL(SUM(DSI_DPP_NET),0) AS TOTAL_DSI_DPP_NET 
FROM V_BRAND_NETSALE 
WHERE 
DSI_DATE >= TRUNC(ADD_MONTHS(SYSDATE, -13), 'MM')
AND DSI_DATE < TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM')
GROUP BY ERP,TO_CHAR(DSI_DATE, 'YYYYMM'),BRAND
ORDER BY BRAND) B ON A.ERP = B.ERP AND A.BRAND = B.BRAND
        ");
                // END PENGIRIMAN DATA -1 BULAN

                Mail::send('mail2', compact('ptsmcb', 'ptseib', 'ptseit', 'ptrjb', 'ptrpm'), function ($message) {
                        $message->to('opayabumanyu@gmail.com', 'DATA')->subject('REPORT');
                        $message->to('arif@smcindonesia.com', 'DATA')->subject('REPORT');
                        $message->to('naufal@smcindonesia.com', 'DATA')->subject('REPORT');
                        $message->from('helpdesk@riyadi.co.id', 'IT');
                });
                echo "Basic Email Sent. Check your inbox.";
        }
}
